name: snaplet-hasql-simple
version: '0.1.0.0'
category: Web
author: Faris Nasution
maintainer: electricladyland156@gmail.com
copyright: 2019 Faris Nasution
license: BSD3
github: nasutiooon/snaplet-hasql-simple
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - ConstraintKinds
  - FlexibleContexts
  - FlexibleInstances
  - RecordWildCards

data-files:
  - resources/devel.cfg

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - snap
    - hasql
    - hasql-pool
    - mtl
    - configurator
    - text
  ghc-options:
    - -Wall
    - -Werror
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
